# Generated by Django 3.2.4 on 2021-07-24 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20210724_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_name', models.CharField(max_length=10)),
                ('Category', models.CharField(choices=[('SCIENCE', 'Science'), ('COMMERCIAL', 'Commercial'), ('ARTS', 'Arts')], max_length=12, null=True)),
                ('Subjects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.teachermore')),
            ],
        ),
    ]
