# Generated by Django 3.2.4 on 2021-07-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='Subjects',
            new_name='Teachers',
        ),
    ]
