# Generated by Django 3.2.4 on 2021-07-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_classes_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='Class_name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
