# Generated by Django 3.2.4 on 2021-07-24 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_classes_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='Teachers',
        ),
    ]
