# Generated by Django 3.2.4 on 2021-07-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_books_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='File',
        ),
    ]
