# Generated by Django 3.2.4 on 2021-07-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_studentmore_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='Category',
            field=models.CharField(choices=[('SCIENCE', 'Science'), ('COMMERCIAL', 'Commercial'), ('ARTS', 'Arts')], max_length=12, null=True),
        ),
    ]
