# Generated by Django 3.2.4 on 2021-07-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210719_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentmore',
            old_name='Staff_id',
            new_name='Parent_id',
        ),
    ]
