# Generated by Django 3.2.4 on 2021-07-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_classes_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmore',
            name='Class',
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
    ]
