# Generated by Django 3.2.4 on 2021-07-21 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_staff_id_parentmore_parent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='parentmore',
            old_name='user',
            new_name='Child',
        ),
        migrations.AlterField(
            model_name='studentmore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AlterField(
            model_name='teachermore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AddField(
            model_name='studentmore',
            name='Class',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='users.classes'),
        ),
    ]
