# Generated by Django 3.2.4 on 2021-07-21 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210721_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='Students',
        ),
        migrations.AddField(
            model_name='classes',
            name='Class_name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='studentmore',
            name='Class',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='users.classes'),
        ),
    ]
