# Generated by Django 3.2.4 on 2021-07-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='First_name',
            new_name='surname',
        ),
        migrations.RemoveField(
            model_name='students',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='students',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Surname',
        ),
        migrations.AddField(
            model_name='teachers',
            name='other_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
    ]
