# Generated by Django 3.2.4 on 2021-07-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='picture',
            field=models.ImageField(blank=True, upload_to='BASE\\passports'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='picture',
            field=models.ImageField(blank=True, upload_to='BASE\\passports'),
        ),
    ]
