# Generated by Django 3.2.4 on 2021-07-14 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Class',
            field=models.ForeignKey(default=django.db.models.deletion.CASCADE, on_delete=django.db.models.deletion.CASCADE, to='classes.school_class'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='Class',
            field=models.ForeignKey(default=django.db.models.deletion.CASCADE, on_delete=django.db.models.deletion.CASCADE, to='classes.school_class'),
        ),
    ]
