# Generated by Django 3.2.4 on 2021-07-14 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('accounts', '0002_auto_20210714_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.school_class'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.school_class'),
        ),
    ]
