# Generated by Django 3.2.4 on 2021-07-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210714_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='Class',
        ),
    ]
